[program:capacity_migrate_gold]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/capacity_migrate_gold.sh
directory=/workspace
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/workspace/logs/capacity_migrate_gold.log
redirect_stderr=true
stdout_logfile_maxbytes=0
