#!/usr/bin/env python3
"""Runtime-validate tests in the unified master Dart CFG+DFG dataset.

This script is intentionally separate from the builder so the dataset never
claims runtime validation when the build host lacks a Dart SDK.  It supports:

* provided `dart_harness` suites;
* generated `differential_program` reference oracles; and
* generated `differential_function` reference oracles.

Without --candidate-dir it validates each suite against the reference source
itself, including repeatability checks.  With --candidate-dir, place candidate
files at <candidate-dir>/<record-id>.dart; the script additionally compares each
candidate to the reference oracle and records pass/fail per row.
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import copy
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Iterable, Iterator

TEST_SCHEMA = "antigravity-behavior-tests-v1"


def iter_jsonl(path: Path) -> Iterator[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig") as f:
        for line_no, line in enumerate(f, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            if not isinstance(row, dict):
                raise TypeError(f"Expected object at {path}:{line_no}")
            yield row


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with path.open("w", encoding="utf-8", newline="\n") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
            count += 1
    return count


def normalize_output(value: str) -> str:
    return value.replace("\r\n", "\n").replace("\r", "\n")


def apply_rewrites(source: str, rules: list[dict[str, Any]]) -> str:
    result = source
    for rule in rules or []:
        pattern = str(rule.get("pattern") or "")
        replacement = str(rule.get("replacement") or "")
        if not pattern:
            continue
        # Rules generated by the builder are literal substitutions.  Regex is
        # supported only when explicitly requested.
        if rule.get("regex"):
            result = re.sub(pattern, replacement, result)
        else:
            result = result.replace(pattern, replacement)
    return result


def _scan_to_matching_brace(text: str, open_index: int) -> int | None:
    depth = 0
    quote: str | None = None
    triple = False
    raw = False
    line_comment = False
    block_depth = 0
    i = open_index
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""
        if line_comment:
            if ch in "\r\n":
                line_comment = False
            i += 1
            continue
        if block_depth:
            if ch == "/" and nxt == "*":
                block_depth += 1
                i += 2
            elif ch == "*" and nxt == "/":
                block_depth -= 1
                i += 2
            else:
                i += 1
            continue
        if quote:
            if triple and text.startswith(quote * 3, i):
                i += 3
                quote = None
                triple = False
                raw = False
                continue
            if not triple and ch == quote:
                i += 1
                quote = None
                raw = False
                continue
            if ch == "\\" and not raw:
                i += 2
            else:
                i += 1
            continue
        if ch == "/" and nxt == "/":
            line_comment = True
            i += 2
            continue
        if ch == "/" and nxt == "*":
            block_depth = 1
            i += 2
            continue
        if ch in "rR" and i + 1 < len(text) and text[i + 1] in "'\"":
            q = text[i + 1]
            triple = text.startswith(q * 3, i + 1)
            quote, raw = q, True
            i += 4 if triple else 2
            continue
        if ch in "'\"":
            quote = ch
            triple = text.startswith(ch * 3, i)
            i += 3 if triple else 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return None


def remove_top_level_main(source: str) -> str:
    """Remove a top-level main body and immediately preceding annotations."""
    pattern = re.compile(
        r"(?m)^[ \t]*(?:(?:Future(?:<[^>]+>)?|void|dynamic|int)\s+)?main\s*\([^)]*\)\s*(?:async\*?|sync\*?)?\s*(?P<body>\{|=>)"
    )
    match = pattern.search(source)
    if not match:
        return source
    start = match.start()
    # Include contiguous annotation lines immediately above the declaration.
    line_start = source.rfind("\n", 0, start) + 1
    scan = line_start
    while scan > 0:
        prev_end = scan - 1
        prev_start = source.rfind("\n", 0, prev_end) + 1
        line = source[prev_start:prev_end].strip()
        if line.startswith("@") or not line:
            scan = prev_start
            continue
        break
    start = scan
    if match.group("body") == "=>":
        semicolon = source.find(";", match.end())
        end = len(source) if semicolon < 0 else semicolon + 1
    else:
        open_index = source.find("{", match.start(), match.end() + 1)
        end = _scan_to_matching_brace(source, open_index) if open_index >= 0 else None
        if end is None:
            return source
    return source[:start].rstrip() + "\n\n" + source[end:].lstrip()


def compose_harness_program(source: str, harness: str, rewrites: list[dict[str, Any]]) -> str:
    base = apply_rewrites(source, rewrites)
    base = remove_top_level_main(base)
    return base.rstrip() + "\n\n" + harness.lstrip() + "\n"


_NORMALIZER = r'''
dynamic _agNormalize(dynamic value) {
  if (value == null || value is num || value is bool || value is String) {
    return value;
  }
  if (value is BigInt) {
    return <String, dynamic>{r'$type': 'BigInt', 'value': value.toString()};
  }
  if (value is List) {
    return value.map(_agNormalize).toList();
  }
  if (value is Set) {
    final items = value.map(_agNormalize).toList();
    items.sort((a, b) => jsonEncode(a).compareTo(jsonEncode(b)));
    return <String, dynamic>{r'$type': 'Set', 'items': items};
  }
  if (value is Map) {
    final entries = value.entries
        .map((e) => <String, dynamic>{'key': _agNormalize(e.key), 'value': _agNormalize(e.value)})
        .toList();
    entries.sort((a, b) => jsonEncode(a['key']).compareTo(jsonEncode(b['key'])));
    return <String, dynamic>{r'$type': 'Map', 'entries': entries};
  }
  if (value is Iterable) {
    return value.map(_agNormalize).toList();
  }
  return <String, dynamic>{
    r'$type': value.runtimeType.toString(),
    'value': value.toString(),
  };
}

Future<void> _agCapture(List<dynamic> output, String label, dynamic Function() action) async {
  try {
    dynamic value = action();
    if (value is Future) value = await value;
    output.add(<String, dynamic>{'label': label, 'ok': true, 'value': _agNormalize(value)});
  } catch (error) {
    output.add(<String, dynamic>{
      'label': label,
      'ok': false,
      'errorType': error.runtimeType.toString(),
      'message': error.toString(),
    });
  }
}
'''


def compose_function_driver(source: str, cases: list[dict[str, Any]], rewrites: list[dict[str, Any]]) -> str:
    base = remove_top_level_main(apply_rewrites(source, rewrites))
    calls: list[str] = []
    for index, case in enumerate(cases):
        call = str(case.get("call") or "").strip()
        label = json.dumps(f"case_{index}")
        calls.append(f"  await _agCapture(_agResults, {label}, () => {call});")
    driver = "\n".join(
        [
            "Future<void> main() async {",
            "  final _agResults = <dynamic>[];",
            *calls,
            "  print(jsonEncode(_agResults));",
            "}",
        ]
    )
    # Imports must precede all declarations. Duplicate imports are legal, but
    # avoid them for cleaner diagnostics.
    prefix = ""
    if "dart:convert" not in base:
        prefix += "import 'dart:convert';\n"
    return prefix + base.rstrip() + "\n\n" + _NORMALIZER.strip() + "\n\n" + driver + "\n"


@dataclass
class RunResult:
    exit_code: int | None
    stdout: str
    stderr: str
    timed_out: bool
    duration_seconds: float

    def comparable(self) -> tuple[int | None, str, str, bool]:
        return (
            self.exit_code,
            normalize_output(self.stdout),
            normalize_output(self.stderr),
            self.timed_out,
        )


def run_dart(dart: str, path: Path, *, stdin_text: str = "", timeout_seconds: float = 10.0) -> RunResult:
    started = time.monotonic()
    try:
        completed = subprocess.run(
            [dart, "run", str(path)],
            input=stdin_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout_seconds,
            cwd=str(path.parent),
            env={**os.environ, "NO_COLOR": "1"},
        )
        return RunResult(
            exit_code=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
            timed_out=False,
            duration_seconds=time.monotonic() - started,
        )
    except subprocess.TimeoutExpired as exc:
        return RunResult(
            exit_code=None,
            stdout=(exc.stdout or "") if isinstance(exc.stdout, str) else "",
            stderr=(exc.stderr or "") if isinstance(exc.stderr, str) else "",
            timed_out=True,
            duration_seconds=time.monotonic() - started,
        )


def summarize_run(result: RunResult, max_chars: int = 2000) -> dict[str, Any]:
    data = asdict(result)
    data["stdout"] = data["stdout"][:max_chars]
    data["stderr"] = data["stderr"][:max_chars]
    return data


def validate_harness(row: dict[str, Any], dart: str, workdir: Path, candidate_source: str | None, timeout: float) -> dict[str, Any]:
    tests = row["tests"]
    reference_program = compose_harness_program(row["dart_source"], tests["harness"], tests.get("rewrite_rules") or [])
    ref_path = workdir / "reference_harness.dart"
    ref_path.write_text(reference_program, encoding="utf-8")
    ref = run_dart(dart, ref_path, timeout_seconds=timeout)
    result: dict[str, Any] = {
        "status": "passed" if ref.exit_code == 0 and not ref.timed_out else "failed",
        "mode": "reference_harness",
        "reference": summarize_run(ref),
    }
    if candidate_source is not None:
        candidate_program = compose_harness_program(candidate_source, tests["harness"], tests.get("rewrite_rules") or [])
        candidate_path = workdir / "candidate_harness.dart"
        candidate_path.write_text(candidate_program, encoding="utf-8")
        candidate = run_dart(dart, candidate_path, timeout_seconds=timeout)
        result["candidate"] = summarize_run(candidate)
        result["candidate_status"] = "passed" if candidate.exit_code == 0 and not candidate.timed_out else "failed"
    return result


def validate_program_oracle(row: dict[str, Any], dart: str, workdir: Path, candidate_source: str | None, timeout: float) -> dict[str, Any]:
    tests = row["tests"]
    reference_source = apply_rewrites(row["dart_source"], tests.get("rewrite_rules") or [])
    ref_path = workdir / "reference.dart"
    ref_path.write_text(reference_source, encoding="utf-8")
    candidate_path = None
    if candidate_source is not None:
        candidate_path = workdir / "candidate.dart"
        candidate_path.write_text(apply_rewrites(candidate_source, tests.get("rewrite_rules") or []), encoding="utf-8")

    retained: list[dict[str, Any]] = []
    case_results: list[dict[str, Any]] = []
    candidate_all_match = True
    for index, case in enumerate(tests.get("cases") or []):
        stdin_text = str(case.get("stdin") or "")
        case_timeout = min(max(float(case.get("timeout_ms") or timeout * 1000) / 1000.0, 0.1), timeout)
        first = run_dart(dart, ref_path, stdin_text=stdin_text, timeout_seconds=case_timeout)
        second = run_dart(dart, ref_path, stdin_text=stdin_text, timeout_seconds=case_timeout)
        reproducible = first.comparable() == second.comparable() and not first.timed_out
        item: dict[str, Any] = {
            "index": index,
            "reproducible": reproducible,
            "reference": summarize_run(first),
        }
        if reproducible:
            retained.append(case)
        if candidate_path is not None and reproducible:
            candidate = run_dart(dart, candidate_path, stdin_text=stdin_text, timeout_seconds=case_timeout)
            matches = candidate.comparable() == first.comparable()
            item["candidate"] = summarize_run(candidate)
            item["candidate_matches_reference"] = matches
            candidate_all_match = candidate_all_match and matches
        case_results.append(item)

    status = "passed" if retained else "failed"
    result: dict[str, Any] = {
        "status": status,
        "mode": "differential_program",
        "stable_case_count": len(retained),
        "input_case_count": len(tests.get("cases") or []),
        "retained_cases": retained,
        "cases": case_results,
    }
    if candidate_path is not None:
        result["candidate_status"] = "passed" if status == "passed" and candidate_all_match else "failed"
    return result


def validate_function_oracle(row: dict[str, Any], dart: str, workdir: Path, candidate_source: str | None, timeout: float) -> dict[str, Any]:
    tests = row["tests"]
    reference_program = compose_function_driver(row["dart_source"], tests.get("cases") or [], tests.get("rewrite_rules") or [])
    ref_path = workdir / "reference_function.dart"
    ref_path.write_text(reference_program, encoding="utf-8")
    first = run_dart(dart, ref_path, timeout_seconds=timeout)
    second = run_dart(dart, ref_path, timeout_seconds=timeout)
    reproducible = first.comparable() == second.comparable() and first.exit_code == 0 and not first.timed_out
    result: dict[str, Any] = {
        "status": "passed" if reproducible else "failed",
        "mode": "differential_function",
        "reproducible": reproducible,
        "reference": summarize_run(first),
        "reference_repeat": summarize_run(second),
    }
    if candidate_source is not None and reproducible:
        candidate_program = compose_function_driver(candidate_source, tests.get("cases") or [], tests.get("rewrite_rules") or [])
        candidate_path = workdir / "candidate_function.dart"
        candidate_path.write_text(candidate_program, encoding="utf-8")
        candidate = run_dart(dart, candidate_path, timeout_seconds=timeout)
        matches = candidate.comparable() == first.comparable()
        result["candidate"] = summarize_run(candidate)
        result["candidate_matches_reference"] = matches
        result["candidate_status"] = "passed" if matches else "failed"
    elif candidate_source is not None:
        result["candidate_status"] = "not_run_reference_failed"
    return result


def validate_one(row: dict[str, Any], *, dart: str, candidate_dir: Path | None, timeout: float) -> dict[str, Any]:
    updated = copy.deepcopy(row)
    tests = updated.get("tests")
    if not isinstance(tests, dict) or tests.get("schema") != TEST_SCHEMA:
        raise ValueError(f"{updated.get('id')}: unsupported test schema")
    candidate_source = None
    candidate_path = None
    if candidate_dir is not None:
        candidate_path = candidate_dir / f"{updated['id']}.dart"
        if candidate_path.is_file():
            candidate_source = candidate_path.read_text(encoding="utf-8-sig")

    with tempfile.TemporaryDirectory(prefix=f"ag_test_{updated['id'][:24]}_") as temp:
        workdir = Path(temp)
        kind = tests.get("kind")
        if kind == "dart_harness":
            runtime = validate_harness(updated, dart, workdir, candidate_source, timeout)
        elif kind == "differential_program":
            runtime = validate_program_oracle(updated, dart, workdir, candidate_source, timeout)
        elif kind == "differential_function":
            runtime = validate_function_oracle(updated, dart, workdir, candidate_source, timeout)
        else:
            runtime = {"status": "failed", "error": f"unsupported test kind: {kind}"}

    runtime["validator"] = "validate_master_dart_tests.py"
    runtime["dart_executable"] = dart
    runtime["candidate_file"] = str(candidate_path) if candidate_path and candidate_path.is_file() else None
    tests.setdefault("validation", {})["runtime"] = runtime
    if kind == "differential_program" and runtime.get("retained_cases"):
        tests["cases"] = runtime["retained_cases"]
        tests["case_count"] = len(runtime["retained_cases"])
    return updated


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--dart", default=None, help="Path to Dart executable; defaults to PATH lookup.")
    parser.add_argument("--candidate-dir", type=Path, default=None, help="Optional directory containing <record-id>.dart candidates.")
    parser.add_argument("--workers", type=int, default=max(1, min(8, os.cpu_count() or 1)))
    parser.add_argument("--timeout", type=float, default=10.0, help="Maximum seconds per Dart invocation.")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--drop-failed", action="store_true", help="Write only rows whose reference test validation passes.")
    parser.add_argument("--summary", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dart = args.dart or shutil.which("dart")
    if not dart:
        raise SystemExit("Dart executable not found. Pass --dart /path/to/dart or add it to PATH.")
    dart = str(Path(dart).resolve()) if os.path.sep in dart else dart
    rows = list(iter_jsonl(args.input))
    if args.limit is not None:
        rows = rows[: args.limit]

    results: list[dict[str, Any] | None] = [None] * len(rows)
    failures: list[dict[str, Any]] = []
    with cf.ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        futures = {
            executor.submit(validate_one, row, dart=dart, candidate_dir=args.candidate_dir, timeout=args.timeout): index
            for index, row in enumerate(rows)
        }
        for future in cf.as_completed(futures):
            index = futures[future]
            try:
                results[index] = future.result()
            except Exception as exc:
                failed = copy.deepcopy(rows[index])
                failed.setdefault("tests", {}).setdefault("validation", {})["runtime"] = {
                    "status": "failed",
                    "validator": "validate_master_dart_tests.py",
                    "error": repr(exc),
                }
                results[index] = failed
                failures.append({"id": rows[index].get("id"), "error": repr(exc)})

    finalized = [row for row in results if row is not None]
    if args.drop_failed:
        finalized = [row for row in finalized if row["tests"]["validation"]["runtime"].get("status") == "passed"]
    write_jsonl(args.output, finalized)

    status_counts: dict[str, int] = {}
    candidate_counts: dict[str, int] = {}
    for row in results:
        assert row is not None
        runtime = row["tests"]["validation"]["runtime"]
        status = str(runtime.get("status"))
        status_counts[status] = status_counts.get(status, 0) + 1
        if "candidate_status" in runtime:
            candidate = str(runtime.get("candidate_status"))
            candidate_counts[candidate] = candidate_counts.get(candidate, 0) + 1
    summary = {
        "input": str(args.input),
        "output": str(args.output),
        "rows_read": len(rows),
        "rows_written": len(finalized),
        "dart": dart,
        "workers": args.workers,
        "timeout": args.timeout,
        "reference_status": status_counts,
        "candidate_status": candidate_counts,
        "exceptions": failures,
    }
    print(json.dumps(summary, indent=2))
    if args.summary:
        args.summary.parent.mkdir(parents=True, exist_ok=True)
        args.summary.write_text(json.dumps(summary, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
