[program:post_qwen_pipeline]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/post_qwen_pipeline.sh
directory=/workspace
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
