[program:multifunction_build_v2]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/multifunction_build_v2.sh
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
