#!/usr/bin/env python3
"""Typed-contract, direct-only RS-SFT over sealed verified targets.

This profile deliberately does not reinterpret the historical evidence.  It
first validates each local/API report with the original mixed-RS-SFT validators
and their original untyped F2 hashes.  Only after that validation succeeds does
it rebind the verified Dart target to the byte-identical opaque typed-contract
source used by the fresh typed SFT arm.

The training schedule contains direct rows only: no gold replay, no local/API
repair-conditioned prefix, no tests, and no private feedback.  Every rebound
target is also re-executed against the task's complete TRAIN acceptance suite;
only the binary outcome and hashes are retained.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import torch

from scripts.evaluation import t5gemma2_f2_passk_inference as inference
from scripts.evaluation.graph_compile_at_k_antigravity import (
    evaluate_dart_jit_tests_detail,
    validate_dart_binary,
)
from scripts.training import t5gemma2_enriched_sft as base_sft
from scripts.training import t5gemma2_mixed_rs_sft as mixed
from scripts.training import t5gemma2_typed_contract_sft as typed_sft


RUN_SCHEMA = "t5gemma2-typed-direct-rs-sft-run-v1"
CHECKPOINT_SCHEMA = "t5gemma2-typed-direct-rs-sft-checkpoint-v1"
DATASET_SCHEMA = "t5gemma2-typed-direct-rs-sft-dataset-v1"

CONTAMINATED_TRAIN_TASK_ID = "sigless_6b1dd0c6b6fc"
EXPECTED_DIRECT_ROWS = 225
EXPECTED_LOCAL_DIRECT_ROWS = 141
EXPECTED_API_DIRECT_ROWS = 84

# The four local ledgers were generated by this exact two-epoch enriched SFT
# adapter.  The checkpoint need not remain on disk: the immutable reports bind
# these three hashes and mixed._validate_local_report checks them directly.
SOURCE_SFT_RUN_CONTRACT_SHA256 = (
    "21613e2c7513e203e31a4690f84b0e6d11fa1c7fa6a20725d859486a30bccac3"
)
SOURCE_SFT_ADAPTER_WEIGHTS_SHA256 = (
    "83d8152edc7236a144fcb7b321f03c4dc5fcf90a1e866fa334338938ee0bdcdc"
)
SOURCE_SFT_ADAPTER_CONFIG_SHA256 = (
    "c21ee4458e7c9fe1321337ce22409ee2a03dfe37299c25cfc7c468a490ffb4c3"
)

FULL_VERIFY_TIMEOUT_SECONDS = 30
FULL_VERIFY_STABILITY_RUNS = 2
FULL_VERIFY_WORKERS = 16

VerifyFn = Callable[[str, str, str], bool]
_MIXED_RUNTIME_CONTRACT = mixed._runtime_contract  # noqa: SLF001


def _canonical_sha256(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    ).hexdigest()


def _source_sft_identity() -> mixed.WarmstartIdentity:
    """Identity needed to validate historical local-harvest reports."""

    return mixed.WarmstartIdentity(
        checkpoint_name="checkpoint-optstep-000348",
        update=348,
        run_contract_sha256=SOURCE_SFT_RUN_CONTRACT_SHA256,
        adapter_weights_sha256=SOURCE_SFT_ADAPTER_WEIGHTS_SHA256,
        adapter_config_sha256=SOURCE_SFT_ADAPTER_CONFIG_SHA256,
        model=base_sft.DEFAULT_MODEL,
        model_revision=inference.MODEL_REVISION,
        lora_rank=64,
        lora_alpha=128,
        lora_dropout=0.05,
        # _validate_local_report does not consume module names; all meaningful
        # source-adapter fields above are checked against each sealed report.
        exact_lora_targets=(),
    )


def validate_typed_warmstart(
    checkpoint: Path,
    *,
    expected_update: int,
    expected_run_contract_sha256: str,
    expected_adapter_weights_sha256: str,
    expected_adapter_config_sha256: str,
    model: str,
    model_revision: str,
) -> tuple[mixed.WarmstartIdentity, dict[str, Any]]:
    """Validate the fresh typed SFT adapter as this stage's only parent."""

    checkpoint = checkpoint.expanduser().resolve()
    contract, record = inference._checkpoint_record(checkpoint, "sft")  # noqa: SLF001
    if contract.get("schema") != typed_sft.RUN_SCHEMA:
        raise ValueError("typed direct RS-SFT requires the fresh typed SFT parent")
    state_path = checkpoint / "training_state.pt"
    if not state_path.is_file():
        raise ValueError("typed warm-start lacks training_state.pt")
    state = torch.load(state_path, map_location="cpu", weights_only=False)
    contract_sha = _canonical_sha256(contract)
    adapter = record.get("adapter")
    if (
        not isinstance(state, Mapping)
        or state.get("schema") != typed_sft.CHECKPOINT_SCHEMA
        or int(state.get("update", -1)) != expected_update
        or state.get("run_contract_sha256") != contract_sha
        or checkpoint.name != base_sft._checkpoint_name(expected_update)  # noqa: SLF001
        or contract_sha
        != mixed._require_sha256(  # noqa: SLF001
            expected_run_contract_sha256, "expected typed warm-start contract"
        )
        or not isinstance(adapter, Mapping)
        or adapter.get("adapter_weights_sha256")
        != mixed._require_sha256(  # noqa: SLF001
            expected_adapter_weights_sha256, "expected typed adapter weights"
        )
        or adapter.get("adapter_config_sha256")
        != mixed._require_sha256(  # noqa: SLF001
            expected_adapter_config_sha256, "expected typed adapter config"
        )
        or contract.get("model") != model
        or contract.get("model_revision") != model_revision
    ):
        raise ValueError("selected typed warm-start checkpoint differs")

    lora = contract.get("lora")
    targets = lora.get("targets") if isinstance(lora, Mapping) else None
    if not isinstance(targets, list) or not targets or len(set(targets)) != len(targets):
        raise ValueError("typed warm-start lacks exact LoRA targets")
    config_path = checkpoint / "adapter" / "adapter_config.json"
    config = mixed._read_json(config_path)  # noqa: SLF001
    identity = mixed.WarmstartIdentity(
        checkpoint_name=checkpoint.name,
        update=expected_update,
        run_contract_sha256=contract_sha,
        adapter_weights_sha256=str(adapter["adapter_weights_sha256"]),
        adapter_config_sha256=str(adapter["adapter_config_sha256"]),
        model=model,
        model_revision=model_revision,
        lora_rank=int(lora.get("rank", -1)),
        lora_alpha=int(lora.get("alpha", -1)),
        lora_dropout=float(lora.get("dropout", -1.0)),
        exact_lora_targets=tuple(sorted(map(str, targets))),
    )
    if (
        identity.lora_rank <= 0
        or identity.lora_alpha <= 0
        or not 0.0 <= identity.lora_dropout < 1.0
        or int(config.get("r", -1)) != identity.lora_rank
        or int(config.get("lora_alpha", -1)) != identity.lora_alpha
        or float(config.get("lora_dropout", -1.0)) != identity.lora_dropout
        or str(config.get("task_type") or "") != "SEQ_2_SEQ_LM"
    ):
        raise ValueError("typed warm-start LoRA configuration differs")
    return identity, contract


def _runtime_verify(code: str, tests: str, slot: str) -> bool:
    compiled, passed, _diagnostic, _details = evaluate_dart_jit_tests_detail(
        code,
        tests,
        slot,
        timeout=FULL_VERIFY_TIMEOUT_SECONDS,
        stability_runs=FULL_VERIFY_STABILITY_RUNS,
    )
    return bool(compiled and passed)


def _complete_tests(row: Mapping[str, Any], task_id: str) -> str:
    tests = row.get("acceptance_tests") or row.get("tests")
    if not isinstance(tests, str) or not tests.strip():
        raise ValueError(f"{task_id}: complete TRAIN acceptance tests are absent")
    return tests


def _verify_all(
    pairs: Sequence[mixed.MixedPair],
    *,
    tests_by_id: Mapping[str, str],
    verify: VerifyFn,
    workers: int,
) -> dict[str, Any]:
    if workers <= 0:
        raise ValueError("verification workers must be positive")

    def one(position: int) -> tuple[int, bool]:
        pair = pairs[position]
        tests = tests_by_id[pair.source_task_id]
        return position, bool(
            verify(pair.target, tests, f"typed-direct-rs-sft-{position:04d}")
        )

    if workers == 1:
        outcomes = [one(index) for index in range(len(pairs))]
    else:
        with ThreadPoolExecutor(max_workers=min(workers, len(pairs))) as pool:
            outcomes = list(pool.map(one, range(len(pairs))))
    failed = [pairs[index].source_task_id for index, passed in outcomes if not passed]
    if failed:
        raise ValueError(
            "typed direct target failed complete acceptance re-verification: "
            + failed[0]
        )
    return {
        "rows": len(pairs),
        "passed": len(pairs),
        "stability_runs": FULL_VERIFY_STABILITY_RUNS,
        "timeout_seconds": FULL_VERIFY_TIMEOUT_SECONDS,
        "diagnostics_persisted": False,
        "tests_model_visible": False,
        "task_ids_sha256": _canonical_sha256(
            [pair.source_task_id for pair in pairs]
        ),
        "acceptance_tests_sha256s_sha256": _canonical_sha256(
            [
                hashlib.sha256(tests_by_id[pair.source_task_id].encode("utf-8")).hexdigest()
                for pair in pairs
            ]
        ),
    }


def build_typed_direct_pairs(
    *,
    gold_train_jsonl: Path,
    gold_f2_jsonl: Path,
    expected_gold_train_sha256: str,
    expected_gold_f2_sha256: str,
    expected_gold_rows: int,
    heldout_jsonl: Path,
    expected_heldout_sha256: str,
    expected_heldout_rows: int,
    local_reports: Sequence[tuple[Path, str]],
    api_reports: Sequence[tuple[Path, str]],
    warmstart: mixed.WarmstartIdentity,
    gold_replay_ratio: float,
    gold_replay_rows: int,
    min_verified_direct_targets: int,
    min_repair_conditioned_targets: int,
    allow_exploratory_inputs: bool,
    require_local_production_floor: bool,
    seed: int,
    verify: VerifyFn | None = None,
    verification_workers: int = FULL_VERIFY_WORKERS,
) -> tuple[list[mixed.MixedPair], dict[str, Any]]:
    """Validate historical ledgers, then build the 225-row typed schedule."""

    del warmstart  # Historical local ledgers bind their own source checkpoint.
    if gold_replay_ratio != 0.0 or gold_replay_rows != 0:
        raise ValueError("typed direct RS-SFT forbids gold replay")
    if min_verified_direct_targets != EXPECTED_DIRECT_ROWS:
        raise ValueError("typed direct RS-SFT requires an exact 225-row floor")
    if min_repair_conditioned_targets != 0:
        raise ValueError("typed direct RS-SFT forbids repair-conditioned rows")
    if allow_exploratory_inputs:
        raise ValueError("typed direct RS-SFT forbids exploratory ledgers")
    if require_local_production_floor:
        # Individual local shards are intentionally smaller than the aggregate.
        raise ValueError("use the aggregate 141-row local floor, not per-shard floors")

    typed_pairs, typed_manifest = typed_sft.load_typed_text_pairs(
        gold_train_jsonl,
        gold_f2_jsonl,
        expected_dataset_sha256=expected_gold_train_sha256,
        expected_f2_sha256=expected_gold_f2_sha256,
        expected_rows=expected_gold_rows,
        heldout_path=heldout_jsonl,
        expected_heldout_sha256=expected_heldout_sha256,
        expected_heldout_rows=expected_heldout_rows,
        exclude_train_task_ids=[CONTAMINATED_TRAIN_TASK_ID],
        allow_unpinned_inputs=False,
    )
    typed_by_id = {pair.task_id: pair for pair in typed_pairs}
    if len(typed_by_id) != len(typed_pairs):
        raise ValueError("typed TRAIN universe contains duplicate task IDs")

    collected: list[tuple[str, mixed.MixedPair]] = []
    report_records: list[dict[str, Any]] = []
    source_identity = _source_sft_identity()
    for path, digest in local_reports:
        pairs, record = mixed._validate_local_report(  # noqa: SLF001
            report_path=path,
            report_sha256=digest,
            warmstart=source_identity,
        )
        if any(pair.kind != "verified_direct" for pair in pairs):
            raise ValueError(f"{path}: local ledger contains a non-direct row")
        collected.extend(("local_student", pair) for pair in pairs)
        report_records.append({**record, "rebind_category": "local_student"})
    for path, digest in api_reports:
        pairs, record = mixed._validate_api_report(  # noqa: SLF001
            report_path=path,
            report_sha256=digest,
            allow_exploratory=False,
        )
        direct = [pair for pair in pairs if pair.kind == "verified_direct"]
        if len(direct) != int(record.get("direct_rows", -1)):
            raise ValueError(f"{path}: API direct-row accounting differs")
        collected.extend(("external_teacher", pair) for pair in direct)
        report_records.append({**record, "rebind_category": "external_teacher"})

    task_ids = [pair.source_task_id for _category, pair in collected]
    if len(set(task_ids)) != len(task_ids):
        raise ValueError("direct ledgers overlap by source task")
    if CONTAMINATED_TRAIN_TASK_ID in task_ids:
        raise ValueError("known train/heldout contaminant entered direct RS-SFT")
    unknown = sorted(set(task_ids) - set(typed_by_id))
    if unknown:
        raise ValueError("direct ledger task is outside clean typed TRAIN: " + unknown[0])
    local_count = sum(category == "local_student" for category, _pair in collected)
    api_count = sum(category == "external_teacher" for category, _pair in collected)
    if (
        len(collected) != EXPECTED_DIRECT_ROWS
        or local_count != EXPECTED_LOCAL_DIRECT_ROWS
        or api_count != EXPECTED_API_DIRECT_ROWS
    ):
        raise ValueError(
            "typed direct composition differs: "
            f"rows={len(collected)}, local={local_count}, api={api_count}"
        )

    rebound: list[mixed.MixedPair] = []
    category_by_id: dict[str, str] = {}
    for category, historical in collected:
        canonical = typed_by_id[historical.source_task_id]
        category_by_id[historical.source_task_id] = category
        rebound.append(
            mixed._make_pair(  # noqa: SLF001
                pair_id=historical.pair_id + "::typed-direct",
                source_task_id=historical.source_task_id,
                kind="verified_direct",
                source=canonical.source,
                target=historical.target,
                provenance=tuple(
                    sorted(
                        set(historical.provenance)
                        | {
                            ("typed_rebind_schema", DATASET_SCHEMA),
                            ("typed_source_sha256", canonical.source_sha256),
                            ("rebind_category", category),
                        }
                    )
                ),
            )
        )

    train_rows = base_sft._read_jsonl(gold_train_jsonl)  # noqa: SLF001
    tests_by_id: dict[str, str] = {}
    gold_target_by_id: dict[str, str] = {}
    for index, row in enumerate(train_rows):
        task_id = base_sft._identity(row, index)  # noqa: SLF001
        if task_id == CONTAMINATED_TRAIN_TASK_ID:
            continue
        tests_by_id[task_id] = _complete_tests(row, task_id)
        gold_target_by_id[task_id] = base_sft._target_source(row, task_id)  # noqa: SLF001
    verification = _verify_all(
        rebound,
        tests_by_id=tests_by_id,
        verify=verify or _runtime_verify,
        workers=verification_workers,
    )

    rebound.sort(
        key=lambda pair: _canonical_sha256(
            {
                "schema": DATASET_SCHEMA,
                "seed": seed,
                "pair_id": pair.pair_id,
                "source_sha256": pair.source_sha256,
                "target_sha256": pair.target_sha256,
            }
        )
    )
    exact_gold = sum(
        pair.target.strip() == gold_target_by_id[pair.source_task_id].strip()
        for pair in rebound
    )
    schedule = [
        {
            "position": position,
            "pair_id": pair.pair_id,
            "source_task_id": pair.source_task_id,
            "kind": "verified_direct",
            "rebind_category": category_by_id[pair.source_task_id],
            "source_sha256": pair.source_sha256,
            "target_sha256": pair.target_sha256,
            "provenance": dict(pair.provenance),
        }
        for position, pair in enumerate(rebound)
    ]
    manifest = {
        "schema": DATASET_SCHEMA,
        "rows": len(rebound),
        "architecture": "native_encoder_decoder",
        "composition": {
            "verified_direct": len(rebound),
            "local_student_direct": local_count,
            "external_teacher_direct": api_count,
            "repair_conditioned": 0,
            "gold_replay": 0,
            "exact_gold_targets_within_direct": exact_gold,
        },
        "gold_replay": {"selected_rows": 0, "forbidden": True},
        "typed_train": typed_manifest,
        "heldout_overlap": 0,
        "known_contaminant_excluded": CONTAMINATED_TRAIN_TASK_ID,
        "model_visible_fields": ["opaque_typed_contract", "F2.text"],
        "tests_model_visible": False,
        "private_feedback_model_visible": False,
        "repair_conditioned_prefixes_visible": False,
        "reports": report_records,
        "full_acceptance_reverification": verification,
        "schedule": schedule,
        "schedule_sha256": _canonical_sha256(schedule),
        "pair_ids_sha256": _canonical_sha256([pair.pair_id for pair in rebound]),
        "source_sha256s_sha256": _canonical_sha256(
            [pair.source_sha256 for pair in rebound]
        ),
        "target_sha256s_sha256": _canonical_sha256(
            [pair.target_sha256 for pair in rebound]
        ),
        "production_floor_eligible": True,
    }
    return rebound, manifest


def _profile_runtime_contract() -> dict[str, str]:
    record = dict(_MIXED_RUNTIME_CONTRACT())
    record["mixed_training_engine_sha256"] = record["trainer_sha256"]
    record["trainer_sha256"] = base_sft.sha256_file(Path(__file__).resolve())
    record["typed_source_builder_sha256"] = base_sft.sha256_file(
        Path(typed_sft.__file__).resolve()
    )
    record["trainer_profile"] = "typed_direct_only_rs_sft_225"
    return record


def _validate_profile_args(args: argparse.Namespace) -> None:
    expected = {
        "gold_replay_ratio": 0.0,
        "gold_replay_rows": 0,
        "min_verified_direct_targets": EXPECTED_DIRECT_ROWS,
        "min_repair_conditioned_targets": 0,
        "epochs": 2,
        "batch_size": 1,
        "gradient_accumulation": 8,
        "max_updates": 0,
        "learning_rate": 2e-5,
        "warmup_ratio": 0.0,
        "seed": 42,
    }
    for name, wanted in expected.items():
        observed = getattr(args, name)
        if isinstance(wanted, float):
            matches = math.isclose(float(observed), wanted, rel_tol=0.0, abs_tol=1e-12)
        else:
            matches = observed == wanted
        if not matches:
            raise ValueError(
                f"typed direct RS-SFT fixes --{name}={wanted}, observed={observed}"
            )
    if args.allow_exploratory_inputs or args.require_local_production_floor:
        raise ValueError("typed direct RS-SFT requires sealed aggregate report inputs")
    if len(args.local_report) != 4 or len(args.api_report) != 7:
        raise ValueError("typed direct RS-SFT requires exactly 4 local and 7 API reports")


def train(args: argparse.Namespace) -> dict[str, Any]:
    _validate_profile_args(args)
    validate_dart_binary()
    originals = {
        "run_schema": mixed.RUN_SCHEMA,
        "checkpoint_schema": mixed.CHECKPOINT_SCHEMA,
        "dataset_schema": mixed.DATASET_SCHEMA,
        "builder": mixed.build_mixed_pairs,
        "warmstart": mixed.validate_warmstart,
        "runtime": mixed._runtime_contract,  # noqa: SLF001
    }
    mixed.RUN_SCHEMA = RUN_SCHEMA
    mixed.CHECKPOINT_SCHEMA = CHECKPOINT_SCHEMA
    mixed.DATASET_SCHEMA = DATASET_SCHEMA
    mixed.build_mixed_pairs = build_typed_direct_pairs
    mixed.validate_warmstart = validate_typed_warmstart
    mixed._runtime_contract = _profile_runtime_contract  # noqa: SLF001
    try:
        return mixed.train(args)
    finally:
        mixed.RUN_SCHEMA = originals["run_schema"]
        mixed.CHECKPOINT_SCHEMA = originals["checkpoint_schema"]
        mixed.DATASET_SCHEMA = originals["dataset_schema"]
        mixed.build_mixed_pairs = originals["builder"]
        mixed.validate_warmstart = originals["warmstart"]
        mixed._runtime_contract = originals["runtime"]  # noqa: SLF001


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    args = mixed.parse_args(argv)
    try:
        _validate_profile_args(args)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    return args


def main(argv: Sequence[str] | None = None) -> int:
    result = train(parse_args(argv))
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
